### ISSUE TITLE
md2mc command not found

### ISSUE THREAD

**Issue by olebrussels** [MarcL/markdown-to-mailchimp#9]
hello, thank you for this great package and your awesome work.
i have installed this package in a folder in my ubuntu machine via npm, when i enter command "md2mc [options]" I get an error reply, command not found, 
I am not very skilled in nodejs or tech so maybe i migh be doing something wrong, 
Do you know if this works in linux? thank you!! 

+ markdown-to-mailchimp@0.5.0
added 219 packages from 225 contributors and audited 220 packages in 11.729s

14 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

manuel@manuel-ThinkPad-X1-Yoga-3rd:~/Documents/ACCION/bigkids/disenhar/places_of_learning/communications/newsletter/markdown_to_mjml$ md2mc [options]
md2mc: command not found
manuel@manuel-ThinkPad-X1-Yoga-3rd:~/Documents/ACCION/bigkids/disenhar/places_of_learning/communications/newsletter/markdown_to_mjml$ -h, --help
-h,: command not found
manuel@manuel-ThinkPad-X1-Yoga-3rd:~/Documents/ACCION/bigkids/disenhar/places_of_learning/communications/newsletter/markdown_to_mjml$ md2mc
md2mc: command not found
manuel@manuel-ThinkPad-X1-Yoga-3rd:~/Documents/ACCION/bigkids/disenhar/places_of_learning/communications/newsletter/markdown_to_mjml$ ^C
manuel@manuel-ThinkPad-X1-Yoga-3rd:~/Documents/ACCION/bigkids/disenhar/places_of_learning/communications/newsletter/markdown_to_mjml$

**Comment by MarcL** [comment]
Hey @olebrussels.

So sorry - I've only just seen this issue now!

What options did you pass on the command line?

You'll need something like this (depending on where your template and markdown files are):

```bash
md2mc -m ./path/to/markdown/file.md -t ./path/to/mjml/template.mjml
```

This will convert a markdown file into HTML using an MJML template.

Let me know what you're trying to achieve and I'll help out. 👍 

Thanks,
Marc

**Comment by olebrussels** [comment]
Hello Marc, thank you for your reply, i am trying to pass that command but i get this message, 

**md2mc: command not found** 

I dont know if you are familiar with this error message. 

Have a nice day!

**Comment by MarcL** [comment]
Have you installed the package locally or globally?
If you install globally then you should have `md2mc` accessible as long as the directory is in your $PATH.
You can install it globally if you just want to use the command-line tool.

To install globally try this:

```bash
npm install -g markdown-to-mailchimp
```

To find out where your global npm modules are installed to try this:

```bash
npm list -g | head -1
```

If you're installing locally then you'll have to ensure that your $PATH contains the current `node_modules` binary path.

To install locally try this:

```bash
npm install markdown-to-mailchimp
```

I have this added to my $PATH which ensures I can always execute locally installed modules and their binary files.
Ad add this to my $PATH:

```
./node_modules/.bin
```

I expose a command-line script as `md2mc` here in the `package.json` file:

https://github.com/MarcL/markdown-to-mailchimp/blob/master/package.json#L6

Does that help?
Let me know if you're still having problems.

Thanks,
Marc

**Comment by olebrussels** [comment]
Hello Marc, thank you for your helpful response, i tried to install it globally but i dont see it in the list of global node_modules. i tried 

npm install -g markdown-to-mailchimp
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/home/manuel/.nvm/versions/node/v14.15.1/bin/md2mc -> /home/manuel/.nvm/versions/node/v14.15.1/lib/node_modules/markdown-to-mailchimp/bin/cli.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules/markdown-to-mailchimp/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ markdown-to-mailchimp@0.5.0
added 230 packages from 226 contributors in 13.604s

**Comment by MarcL** [comment]
Thanks for the update @olebrussels.

Looking at the above, I think you've installed it globally. (As an aside, I will fix the deprecated package issue!)
This should show you the top-level `npm` packages installed:

```bash
npm list -g --depth 0
```

For me, after I've installed it I see:

```bash
/Users/myusername/.nvm/versions/node/v12.18.2/lib
├── firebase-tools@8.15.1
├── markdown-to-mailchimp@0.5.0
├── npm@6.14.5
├── serverless@2.15.0
└── yarn@1.22.4
```

If you type this, it should show where it was installed:

```bash
where md2mc
```

Check that the directory shown from the above is in your $PATH variable or you won't find the executable.

Does that help?

**Comment by MarcL** [comment]
I'm assuming this is working as expected now but feel free to open another issue if not. Thanks!
